.TH GREYDBD 8 "1.0" "May 30, 2012" ""
.SH NAME
.B greydbd
\- spamilter greylist support database service
.SH SYNOPSIS
greydbd [-v] [-d] [-p port number] [-h psql hostname] [-i psql host port] [-j psql database device name] [-k psql database user name] [-l psql database user password]
.br
.SH OPTIONS
.TP
.B -v
display version
.TP
.B -p
service port number
.TP
.B -h
psql hostname
.TP
.B -i
psql host port
.TP
.B -j
psql database device name
.TP
.B -k
psql database user name
.TP
.B -l
psql database user password
.SH DESCRIPTION
provides a database storage and aging mechanisim to track ipaddress and email tuples.
.br
.SH VERSION
This documentation describes
.B greydbd
version 1.0
.SH "SEE ALSO"
spamilter(8), ipfwmtad(8)
.br
.I http://www.wanlink.com/spamilter/ site
.SH AUTHOR
.br
Neal Horman <spamilter@wanlink.com>
