.TH IPFWMTAD 8 "0.60" "May 30, 2012" ""
.SH NAME
.B ipfwmtad
\- ipfw firewall rule injection daemon
.SH SYNOPSIS
ipfwmtad [-dp -n fname] [-u rule number] [ [-i fname] | [-r ipaddress] | [-q ipaddress] | [-a ipaddress] | [-q ipaddress] ]
.br
.SH OPTIONS

.TP
.B -d
debug mode
.TP
.B -p
server mode - tcp port number - default = 4739
.TP
.B -n
server mode - ip database file name - default = /tmp/ipfwmtad.db
.TP
.B -u
server mode - ipfw rule number - default = 90
.TP
.B -b
server mode - ipfw action (add/deny)
.TP
.B -i
imeadiate mode - ipfw resync using the ip database file name
.TP
.B -r
imeadiate mode - queue ipaddress for removal
.TP
.B -a
imeadiate mode - queue ipaddress for addition
.TP
.B -q
imeadiate mode - query ipaddress 

.SH DESCRIPTION
maintains and ages a list of ip addresses as submitted by
.B spamilter
for rate limiting and blocking
.br
.SH VERSION
This documentation describes
.B ipfwmtad
version 0.60
.SH "SEE ALSO"
spamilter(8), greydbd(8)
.br
.I http://www.wanlink.com/spamilter/ site
.SH AUTHOR
.br
Neal Horman \<spamilter@wanlink.com\>
